module Lambda.AnotherTest

open Expecto
open AWSTest.Common

[<Tests>]
let tests =
  testList "reqwrewrw" [
    testAsync "loles" {
      let cloudwatchEvents = getResultForAllAccounts getCloudWatchEvents
      let actual = cloudwatchEvents
                   |> Seq.collect(fun x -> x.Result
                                         |> Seq.map(fun i -> {| AccountName = x.AccountName; RuleName = i.Name; ScheduleExpression = i.ScheduleExpression |}))
                   |> Seq.filter(fun result -> ["gss-green-down-schedule"; "gss-green-up-schedule"; "ec2-auto-start-schedule"; "ec2-auto-stop-schedule"; "ecs-start-scheduler"; "ecs-stop-scheduler"] |> Seq.contains result.RuleName)
              
      let expected = seq {
          {| AccountName = "hud-shared-service"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-shared-service"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-shared-service"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-shared-service"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-shared-service"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-shared-service"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-gss-sandbox"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 11 ? * MON-FRI *)"|}
          {| AccountName = "hud-gss-sandbox"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-gss-sandbox"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 11 ? * MON-FRI *)"|}
          {| AccountName = "hud-gss-sandbox"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-gss-sandbox"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-gss-sandbox"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 11 ? * MON-FRI *)"|}
          {| AccountName = "hud-cares-dev"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-cares-dev"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-cares-dev"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-cares-dev"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-cares-dev"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-cares-dev"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-cares-prod"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-cares-prod"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-cares-prod"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-cares-prod"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-cares-prod"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-cares-prod"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-cares-sandbox"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 6 ? 1 2L /5)"|}
          {| AccountName = "hud-cares-sandbox"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-cares-sandbox"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 6 ? 1 2L /5)"|}
          {| AccountName = "hud-cares-sandbox"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-cares-sandbox"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-cares-sandbox"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 6 ? 1 2L /5)"|}
          {| AccountName = "hud-claims-dev"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 10 ? * MON-FRI *)"|}
          {| AccountName = "hud-claims-dev"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-claims-dev"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-claims-dev"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-claims-dev"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-claims-dev"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-claims-prod"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 10 ? * MON-FRI *)"|}
          {| AccountName = "hud-claims-prod"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 1 * * ? *)"|}
          {| AccountName = "hud-claims-prod"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-claims-prod"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 1 * * ? *)"|}
          {| AccountName = "hud-claims-prod"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 1 * * ? *)"|}
          {| AccountName = "hud-claims-prod"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-claims-sandbox"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-claims-sandbox"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-claims-sandbox"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-claims-sandbox"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-claims-sandbox"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-claims-sandbox"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-dap-dev"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-dap-dev"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-dap-dev"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-dap-dev"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-dap-dev"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-dap-dev"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-dap-prod"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-dap-prod"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-dap-prod"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-dap-prod"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-dap-prod"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-dap-prod"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 6 ? 1 2L /5)"|}
          {| AccountName = "hud-dap-sandbox"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-dap-sandbox"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-dap-sandbox"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-dap-sandbox"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-dap-sandbox"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-dap-sandbox"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-eap-dev"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 6 ? 1 2L /5)"|}
          {| AccountName = "hud-eap-dev"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-eap-dev"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 6 ? 1 2L /5)"|}
          {| AccountName = "hud-eap-dev"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-eap-dev"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-eap-dev"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 6 ? 1 2L /5)"|}
          {| AccountName = "hud-eap-prod"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 6 ? 1 2L /5)"|}
          {| AccountName = "hud-eap-prod"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-eap-prod"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 6 ? 1 2L /5)"|}
          {| AccountName = "hud-eap-prod"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-eap-prod"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-eap-prod"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 6 ? 1 2L /5)"|}
          {| AccountName = "hud-eap-sandbox"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 6 ? 1 2L /5)"|}
          {| AccountName = "hud-eap-sandbox"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-eap-sandbox"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 6 ? 1 2L /5)"|}
          {| AccountName = "hud-eap-sandbox"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-eap-sandbox"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-eap-sandbox"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 6 ? 1 2L /5)"|}
          {| AccountName = "hud-eda-sdlc"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-eda-sdlc"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-eda-sdlc"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-eda-sdlc"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-eda-sdlc"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-eda-sdlc"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-eda-prod"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-eda-prod"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-eda-prod"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-eda-prod"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-eda-prod"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 0 * * ? *)"|}
          {| AccountName = "hud-eda-prod"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-eda-sandbox"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-eda-sandbox"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-eda-sandbox"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-eda-sandbox"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-eda-sandbox"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-eda-sandbox"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-enterprise-service-dev"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-enterprise-service-dev"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-enterprise-service-dev"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-enterprise-service-dev"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-enterprise-service-dev"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-enterprise-service-dev"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-enterprise-service-prod"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-enterprise-service-prod"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-enterprise-service-prod"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-enterprise-service-prod"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-enterprise-service-prod"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-enterprise-service-prod"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-enterprise-service-sandbox"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-enterprise-service-sandbox"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-enterprise-service-sandbox"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-enterprise-service-sandbox"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-enterprise-service-sandbox"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-enterprise-service-sandbox"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-innovation-dev"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-innovation-dev"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-innovation-dev"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-innovation-dev"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-innovation-dev"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-innovation-dev"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-onap-nonprod"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-onap-nonprod"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 4 * * ? *)"|}
          {| AccountName = "hud-onap-nonprod"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-onap-nonprod"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 4 * * ? *)"|}
          {| AccountName = "hud-onap-nonprod"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 4 * * ? *)"|}
          {| AccountName = "hud-onap-nonprod"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-onap-prod"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-onap-prod"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-onap-prod"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-onap-prod"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-onap-prod"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-onap-prod"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-onap-sandbox"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-onap-sandbox"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-onap-sandbox"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-onap-sandbox"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-onap-sandbox"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-onap-sandbox"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-opfund-dev"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-opfund-dev"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-opfund-dev"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-opfund-dev"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-opfund-dev"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-opfund-dev"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-opfund-prod"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-opfund-prod"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-opfund-prod"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-opfund-prod"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-opfund-prod"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-opfund-prod"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-opfund-sandbox"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-opfund-sandbox"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-opfund-sandbox"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-opfund-sandbox"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-opfund-sandbox"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-opfund-sandbox"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-servicing-dev"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 11 ? * MON-FRI *)"|}
          {| AccountName = "hud-servicing-dev"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 1 * * ? *)"|}
          {| AccountName = "hud-servicing-dev"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-servicing-dev"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-servicing-dev"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-servicing-dev"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-servicing-prod"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 11 ? * MON-FRI *)"|}
          {| AccountName = "hud-servicing-prod"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 1 * * ? *)"|}
          {| AccountName = "hud-servicing-prod"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-servicing-prod"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-servicing-prod"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-servicing-prod"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-servicing-sandbox"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 11 ? * MON-FRI *)"|}
          {| AccountName = "hud-servicing-sandbox"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 1 * * ? *)"|}
          {| AccountName = "hud-servicing-sandbox"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-servicing-sandbox"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-servicing-sandbox"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-servicing-sandbox"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-torch-dev"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 11 ? * MON-FRI *)"|}
          {| AccountName = "hud-torch-dev"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 3 * * ? *)"|}
          {| AccountName = "hud-torch-dev"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 11 ? * MON-FRI *)"|}
          {| AccountName = "hud-torch-dev"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 3 * * ? *)"|}
          {| AccountName = "hud-torch-dev"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 3 * * ? *)"|}
          {| AccountName = "hud-torch-dev"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 11 ? * MON-FRI *)"|}
          {| AccountName = "hud-torch-prod"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 11 ? * MON-FRI *)"|}
          {| AccountName = "hud-torch-prod"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 3 * * ? *)"|}
          {| AccountName = "hud-torch-prod"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 11 ? * MON-FRI *)"|}
          {| AccountName = "hud-torch-prod"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 3 * * ? *)"|}
          {| AccountName = "hud-torch-prod"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 3 * * ? *)"|}
          {| AccountName = "hud-torch-prod"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 11 ? * MON-FRI *)"|}
          {| AccountName = "hud-torch-sandbox"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-torch-sandbox"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-torch-sandbox"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-torch-sandbox"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-torch-sandbox"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-torch-sandbox"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-tracs-dev"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-tracs-dev"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-tracs-dev"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-tracs-dev"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-tracs-dev"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-tracs-dev"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-tracs-prod"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-tracs-prod"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-tracs-prod"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(5 12 ? * MON-FRI *)"|}
          {| AccountName = "hud-tracs-prod"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-tracs-prod"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-tracs-prod"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 6 ? 1 2L /5)"|}
          {| AccountName = "hud-tracs-sandbox"; RuleName = "ec2-auto-start-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-tracs-sandbox"; RuleName = "ec2-auto-stop-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-tracs-sandbox"; RuleName = "ecs-start-scheduler"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
          {| AccountName = "hud-tracs-sandbox"; RuleName = "ecs-stop-scheduler"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-tracs-sandbox"; RuleName = "gss-green-down-schedule"; ScheduleExpression = "cron(0 21 * * ? *)"|}
          {| AccountName = "hud-tracs-sandbox"; RuleName = "gss-green-up-schedule"; ScheduleExpression = "cron(0 12 ? 1 2L /5)"|}
      }        
      Expect.sequenceContainsOrder actual expected "Lambdas scheduler environment tag does not have the expected value."
      }
      ] |> testLabel "cloudwatch event rules"